import { createSlice } from '@reduxjs/toolkit';
import { userActions } from './user.actions';
import { UserState } from './userSlice.types';

const initialState: UserState = {
    recentSearchedProfiles: [],
    desoUser: [],
    isFetchingDesofyUser: false,
    desofyUser: undefined,
    adminAccess: false,
    hasFetchedAdminAccess: false,
    hasFetchedPromotionAccess: false,
    lastProfilePostsFetched: '',
    lastFollowersFollowingsFetched: '',
    lastProfileDiamondsFetched: '',
    loggedInUserStats: {
        nft_earnings: 0,
        fr_earnings_nanos: 0,
        diamonds_value_r: 0,
    },
    userStats: {
        actor: '',
        transactions: 0,
        likes_r: 0,
        likes_g: 0,
        follows_r: 0,
        follows_g: 0,
        diamonds_r: 0,
        diamonds_g: 0,
        diamonds_value_r: 0,
        diamonds_value_g: 0,
        posts: 0,
        replies_g: 0,
        reclouts_g: 0,
        quoted_reclouts_g: 0,
        replies_r: 0,
        reclouts_r: 0,
        quoted_reclouts_r: 0,
        first_txn_time: '',
        last_txn_time: '',
        profile_txn_time: '',
        username: '',
        description: '',
        fr: 0,
        total_fee_nanos: 0,
        fr_earnings_nanos: 0,
        accepted_nft_paid_additional_creator_royalties_nanos: 0,
        accepted_nft_paid_additional_creator_coin_royalties_nanos: 0,
        buynow_nft_paid_additional_creator_royalties_nanos: 0,
        buynow_nft_paid_additional_creator_coin_royalties_nanos: 0,
        total_accepted_nft_nanos: 0,
        accepted_nft_bid_paid_creator_royalty_nanos: 0,
        accepted_nft_bid_paid_creator_coin_royalty_nanos: 0,
        net_accepted_nft_nanos: 0,
        total_buynow_nft_nanos: 0,
        buynow_nft_bid_paid_creator_royalty_nanos: 0,
        buynow_nft_bid_paid_creator_coin_royalty_nanos: 0,
        net_buynow_nft_nanos: 0,
        accepted_nft_bid_received_creator_royalty_nanos: 0,
        accepted_nft_bid_received_additional_creator_royalties_nanos: 0,
        buynow_nft_bid_received_creator_royalty_nanos: 0,
        buynow_nft_bid_received_additional_creator_royalties_nanos: 0,
        net_nft_bid_nanos: 0,
        nft_received_royalties_nanos: 0,
        nft_earnings: 0,
        total_earnings: 0,
    },
    userProfile: undefined,
    topCreatorProfiles: [],
    unReadNotificationCount: 0,
};

export const userSlice = createSlice({
    name: 'user',
    initialState: initialState,
    reducers: userActions,
});

export const {
    setInitialRecentSearchedProfiles,
    addRecentSearchedProfile,
    removeRecentSearchedProfile,
    clearAllRecentSearchedProfiles,
    setUserStateless,
    setUserStats,
    setDesofyUserData,
    setLoggedInUserStats,
    setLastProfileDiamondsFetched,
    setLastProfilePostsFetched,
    setLastFollowersFollowingsFetched,
    setIsFetchingDesofyUser,
    removeTwitterLink,
    removeUserFromState,
    setAdminAccess,
    setUserProfile,
    setTopCreatorProfiles,
    setPinnedPostHashHex,
    setUnReadNotificationCount,
} = userSlice.actions;

export const userReducer = userSlice.reducer;
